name: int256 CI

concurrency:
  group: ci-workflow-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-v**
  pull_request:

jobs:
  lint:
    name: Run golangci-lint
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          check-latest: true
          cache: false
          cache-dependency-path: |
            go.sum
            go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          only-new-issues: false
          skip-cache: true
          skip-save-cache: true
          working-directory: .
          args: --timeout=10m

  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          check-latest: true
          cache: false
          cache-dependency-path: |
            go.sum
            go.mod
      - name: Run tests
        run: go test -race -coverprofile cover.out -vet=off ./...
      - name: Print coverage
        run: |
          go tool cover -func cover.out | grep total | awk '{notice="Statement Coverage: " substr($3, 1, length($3))} END {print notice}'
